version: "3"
services:
  client:
    build: ./client
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
      - /client/node_modules
    links:
      - bids_api
      - users_api
      - regions_api
    networks:
      - webappnetwork
  bids_api:
    build: ./bids-api
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./bids-api:/bids-api
      - /bids-api/node_modules
    depends_on:
      - mongodb
    networks:
      - webappnetwork
  users_api:
    build: ./users-api
    restart: always
    ports:
      - "3002:3002"
    volumes:
      - ./users-api:/users-api
      - /users-api/node_modules
    depends_on:
      - mongodb
    networks:
      - webappnetwork
  regions_api:
    build: ./regions-blockchain
    restart: always
    ports:
      - "3003:3003"
    volumes:
      - ./regions-blockchain:/regions-blockchain
      - /regions-blockchain/node_modules
    depends_on:
      - mongodb
    networks:
      - webappnetwork
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - ./data-node:/data/db
    ports:
      - 27017:27017
    command: mongod --noauth --smallfiles
    networks:
      - webappnetwork

networks:
  webappnetwork:
    driver: bridge
