version: "3"
services:
  users-api:
    container_name: users-api
    restart: always
    build: .
    ports:
      - "3002:3002"
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  client:
    container_name: client
    restart: always
    build: .
    ports:
      - "3000:3000"
      
  
