version: "3"
services:
  app:
    container_name: users-api
    restart: always
    build: .
    ports:
      - "3002:3002"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - "27018:27018"
  
